### ISSUE TITLE
Irrelevant Issue

### ISSUE THREAD

**Issue by MrSlimCoder** [Mohammad-Quanit/Mohammad-Quanit.github.io#1]
Hello dude! i liked your portfolio template and i modify it for my need without your permission , but i have given credit to you in my portfolio repository check this repo [portfolio](https://github.com/viveksharmaui/Portfolio) 
Thanks for this beautiful design .

**Comment by MrSlimCoder** [comment]
I opened this issue because i just want to thanks you 🙂

**Comment by mohammad-quanit** [comment]
I am glad you loved it, bro, @viveksharmaui
